// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebDeveloper.Core.Entities
{
    [Table("Artist")]
    public partial class Artist
    {
        public Artist()
        {
            Albums = new HashSet<Album>();
        }

        public int ArtistId { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "La longitud debe ser maximo de 5 caracteres")]
        public string Name { get; set; }

        public virtual ICollection<Album> Albums { get; set; }
    }
}